export interface Product {
  id: string;
  brand: string;
  name: string;
  type: "oil" | "vinegar";
  description: string;
  size: string;
  price: number;
  image?: string;
  isPromo?: boolean;
  hasCart?: boolean;
  intensity?: "suave" | "medio" | "intenso";
  oliveVarieties?: string[];
  region?: string;
  tasting?: string[];
}

export const intensityOptions = [
  { value: "suave", label: "Suave", description: "Sabor delicado y mantecoso" },
  {
    value: "medio",
    label: "Medio",
    description: "Sabor equilibrado y versátil",
  },
  {
    value: "intenso",
    label: "Intenso",
    description: "Sabor robusto y herbáceo",
  },
];

export const oliveVarieties = [
  { value: "arbequina", label: "Arbequina" },
  { value: "coratina", label: "Coratina" },
  { value: "genovesa", label: "Genovesa" },
  { value: "picual", label: "Picual" },
  { value: "blend", label: "Blend" },
  { value: "otros", label: "Otros" },
];

export const products: Product[] = [
  {
    id: "1",
    brand: "Olei & Co.",
    name: "Dúo Vasija",
    type: "oil",
    description:
      "Virgen Extra + Aceto Balsámico Reducción · Incluye bolsita de tela de transporte",
    size: "Combo 2 x 250ml",
    price: 29900,
    image: "/products/duo.png",
    isPromo: true,
    hasCart: true,
    intensity: "medio",
    oliveVarieties: ["blend"],
    region: "Mendoza",
    tasting: ["elegante", "equilibrado", "versátil"],
  },
  {
    id: "2",
    brand: "Oliovita",
    name: "Mediterráneo",
    type: "oil",
    description: "Virgen Extra",
    size: "250ml",
    price: 6700,
    image: "/products/oliovita-mediterraneo.png",
    hasCart: true,
    intensity: "medio",
    oliveVarieties: ["arbequina"],
    region: "San Juan",
    tasting: ["mantecoso", "suave", "delicado"],
  },
  {
    id: "3",
    brand: "Oliovita",
    name: "Clásico",
    type: "oil",
    description: "Virgen Extra",
    size: "250ml",
    price: 7300,
    image: "/products/oliovita-clasico.png",
    hasCart: true,
    intensity: "medio",
    oliveVarieties: ["blend"],
    region: "San Juan",
    tasting: ["equilibrado", "fresco", "afrutado"],
  },
  {
    id: "4",
    brand: "Tupelí",
    name: "Extra Virgen",
    type: "oil",
    description: "San Juan",
    size: "250ml",
    price: 8900,
    image: "/products/tupeli-250.png",
    hasCart: true,
    intensity: "medio",
    oliveVarieties: ["coratina"],
    region: "San Juan",
    tasting: ["herbáceo", "robusto", "picante"],
  },
  {
    id: "5",
    brand: "Laur",
    name: "Virgen Extra",
    type: "oil",
    description: "Mendoza Argentina",
    size: "250ml",
    price: 10900,
    image: "/products/laur.png",
    hasCart: true,
    intensity: "suave",
    oliveVarieties: ["picual"],
    region: "Mendoza",
    tasting: ["intenso", "herbáceo", "premium"],
  },
  {
    id: "6",
    brand: "Familia Zuccardi",
    name: "Coratina",
    type: "oil",
    description: "Variedad Mendoza",
    size: "250ml",
    price: 11400,
    image: "/products/coratina_final.png",
    hasCart: true,
    intensity: "intenso",
    oliveVarieties: ["coratina"],
    region: "Mendoza",
    tasting: ["robusto", "especiado", "complejo"],
  },
  {
    id: "7",
    brand: "Familia Zuccardi",
    name: "Genovesa",
    type: "oil",
    description: "Variedad Mendoza",
    size: "250ml",
    price: 11400,
    image: "/products/genovesa_final.png",
    hasCart: true,
    intensity: "medio",
    oliveVarieties: ["genovesa"],
    region: "Mendoza",
    tasting: ["elegante", "frutal", "equilibrado"],
  },
  {
    id: "8",
    brand: "Familia Zuccardi",
    name: "Picual",
    type: "oil",
    description: "Variedad Mendoza",
    size: "250ml",
    price: 11400,
    image: "/products/picual_final.png",
    hasCart: true,
    intensity: "intenso",
    oliveVarieties: ["picual"],
    region: "Mendoza",
    tasting: ["potente", "herbáceo", "mineral"],
  },
  {
    id: "9",
    brand: "Zuelo",
    name: "Original",
    type: "oil",
    description: "Virgen Extra",
    size: "250ml",
    price: 11700,
    image: "/products/zuelo-original.png",
    hasCart: true,
    intensity: "medio",
    oliveVarieties: ["blend"],
    region: "Argentina",
    tasting: ["fresco", "afrutado", "versátil"],
  },
  {
    id: "10",
    brand: "Hilal",
    name: "Blend Doña Sofía",
    type: "oil",
    description: "Virgen Extra · Envase PET",
    size: "500ml",
    price: 12900,
    image: "/products/hilal.png",
    hasCart: true,
    intensity: "medio",
    oliveVarieties: ["blend"],
    region: "Argentina",
    tasting: ["suave", "mantecoso", "accesible"],
  },
  {
    id: "11",
    brand: "Tupelí",
    name: "Extra Virgen",
    type: "oil",
    description: "Mendoza",
    size: "500ml",
    price: 14700,
    image: "/products/tupeli-500.png",
    hasCart: true,
    intensity: "medio",
    oliveVarieties: ["coratina"],
    region: "Mendoza",
    tasting: ["herbáceo", "robusto", "picante"],
  },
  {
    id: "12",
    brand: "Hilal",
    name: "Blend Doña Sofía",
    type: "oil",
    description: "Virgen Extra · Envase de Vidrio",
    size: "500ml",
    price: 15200,
    image: "/products/hilal-55-v.png",
    hasCart: true,
    intensity: "medio",
    oliveVarieties: ["blend"],
    region: "Argentina",
    tasting: ["equilibrado", "suave", "afrutado"],
  },
  {
    id: "18",
    brand: "Olei & Co.",
    name: "Jarra",
    type: "oil",
    description:
      "Extra Virgen Blend · Origen Mendoza · Bolsita de tela de regalo",
    size: "500ml",
    price: 29900,
    image: "/products/olei-500.png",
    hasCart: true,
    intensity: "medio",
    oliveVarieties: ["blend"],
    region: "Mendoza",
    tasting: ["complejo", "herbáceo", "premium"],
  },
  {
    id: "14",
    brand: "Zuelo",
    name: "Blend Original",
    type: "oil",
    description: "Virgen Extra",
    size: "500ml",
    price: 17600,
    image: "/products/zuelo-500.png",
    hasCart: true,
    intensity: "medio",
    oliveVarieties: ["blend"],
    region: "Argentina",
    tasting: ["fresco", "equilibrado", "versátil"],
  },
  {
    id: "15",
    brand: "Familia Zuccardi",
    name: "Genovesa",
    type: "oil",
    description: "Variedad Mendoza",
    size: "500ml",
    price: 19900,
    image: "/products/genovesa-500.png",
    hasCart: true,
    intensity: "medio",
    oliveVarieties: ["genovesa"],
    region: "Mendoza",
    tasting: ["elegante", "frutal", "sofisticado"],
  },
  {
    id: "16",
    brand: "El Mistol",
    name: "Premium",
    type: "oil",
    description: "Virgen Extra",
    size: "500ml",
    price: 20300,
    image: "/products/Mistol.png",
    hasCart: true,
    intensity: "medio",
    oliveVarieties: ["blend"],
    region: "Argentina",
    tasting: ["robusto", "complejo", "premium"],
  },
  {
    id: "17",
    brand: "Hilal",
    name: "Blend Doña Sofía",
    type: "oil",
    description: "Virgen Extra · Envase PET",
    size: "1 Litro",
    price: 23900,
    image: "/products/hilal-1L.png",
    hasCart: true,
    intensity: "medio",
    oliveVarieties: ["blend"],
    region: "Argentina",
    tasting: ["suave", "mantecoso", "accesible"],
  },
];

export const awards = [
  {
    brand: "Oliovita",
    title: "Destacados",
    achievements: [
      "TerraOlivo (Israel): Grand Prestige Gold, Prestige Gold y Gold para Changlot, Arbequina, Aprile y Coratina (2023)",
      "EVO IOOC (Italia): medallas internacionales (ej. plata) en distintas variedades (2023)",
      "London International Olive Oil Competition: medallas de calidad en distintas variedades (2024)",
      "Brazil IOOC: medallas en categorías de AOVE (2021)",
      "Expoliva (Jaén, España): distinciones para varietales de la marca (2023)",
      "Olive Japan / Japan Olive Oil Prize: medalla de plata (Coratina) (2025)",
    ],
  },
  {
    brand: "Laur",
    title: "Ranking",
    achievements: [
      "EVOO World Ranking: N.º 1 del mundo por tres años consecutivos, primera aceitera fuera de Europa en lograrlo",
      "Tricampeonato mundial: confirmó su liderazgo global en enero de 2024",
      "Laur Gran Mendoza: múltiples oros en NYIOOC y EVO IOOC (2023-2024)",
      "Laur Altos Limpios: Best Extra Virgin Olive Oil de Argentina (Athena IOOC, Grecia) (2023)",
      "Laur Alto en Polifenoles: oro y Best of the Best (BAIOOC) (2023)",
      "Medallas en Europa: 6 oros en certámenes de Atenas y Londres (London IOOC) (2023)",
    ],
  },
  {
    brand: "Familia Zuccardi",
    title: "Excelencia",
    achievements: [
      "Premio Mario Solinas (COI): Primer Premio Hemisferio Sur para Arauco Selección de Finca (2025)",
      "Olive Japan: Best of the Show por tercer año consecutivo (Zuccardi Arauco) (2024)",
      "NYIOOC: medalla de oro para su monovarietal orgánico (2024)",
      "ArgOliva: posiciones destacadas en el concurso nacional de San Juan",
      "Trayectoria: más de 100 galardones internacionales en 20 cosechas (dic. 2024)",
    ],
  },
  {
    brand: "El Mistol",
    title: "Medallas",
    achievements: [
      "NYIOOC: medalla de oro (2023)",
      "EVO IOOC (Italia): oros (2023, 2021, 2016)",
      "Terraolivo IOOC: oros (2022, 2015)",
      "London Olive Oil Awards (LIOOC): plata en categoría Blend (2024)",
      "Olvinus: Gran Prestigio Oro (2025)",
    ],
  },
];
